# Generated by Django 3.2.8 on 2025-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20250405_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='age',
            field=models.FloatField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
