# Generated by Django 3.2.8 on 2025-04-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_userlist_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
