# Generated by Django 3.2.8 on 2025-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_userlist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='competition_honors',
            field=models.TextField(blank=True, null=True, verbose_name='竞赛荣誉'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='professional_skills',
            field=models.TextField(blank=True, null=True, verbose_name='专业技能'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='school_position',
            field=models.TextField(blank=True, null=True, verbose_name='校园经历'),
        ),
    ]
