# Generated by Django 3.2.8 on 2025-04-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20250405_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlist',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('written_test', '笔试'), ('first_interview', '一面'), ('second_interview', '二面')], default='pending', max_length=20),
        ),
    ]
